-- AlterTable
ALTER TABLE "User" ALTER COLUMN "activateAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "subscribedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "subscriptionStart" SET DEFAULT CURRENT_TIMESTAMP;
