"use client";

import type React from "react";
import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "am" | "om";

type LanguageContextType = {
	language: Language;
	setLanguage: (lang: Language) => void;
	t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(
	undefined
);

const translations: Record<Language, Record<string, string>> = {
	en: {
		home: "Home",
		categories: "Categories",
		profile: "Profile",
		more: "More",
		latestNews: "Latest News",
		featured: "Featured",
		search: "Search",
		back: "Back",
		share: "Share",
		likes: "Likes",
		comments: "Comments",
		save: "Save",
		relatedArticles: "Related Articles",
		favoriteSports: "Favorite Sports",
		savedArticles: "Saved Articles",
		settings: "Settings",
		sportsEnthusiast: "Sports Enthusiast",
		majorUpset: "Major Upset in Championship Game",
		shortDescription: "Short description of the news item...",
		readMore: "Read More",
		national: "National",
		international: "International",
		sportHistory: "Sport History",
		ethiopianAthletics: "Ethiopian Athletics",
		football: "Football",
		basketball: "Basketball",
		tennis: "Tennis",
		f1: "F1",
		subcategories: "Subcategories",
		menu: "Menu",
		becomeAWriter: "Become a Writer",
		aboutUs: "About Us",
		aboutUsShort:
			"8436 Insight is your daily destination for sports news, bringing you the latest updates from around the globe. Stay informed with the most current sports news and developments",
		contactUs: "Contact Us",
		termsOfUse: "Terms of Use",
		getInTouch: "Get In Touch",
		writerLogin: "Writer Login",
		writerRegister: "Writer Registration",
		fullName: "Full Name",
		email: "Email",
		password: "Password",
		confirmPassword: "Confirm Password",
		login: "Login",
		register: "Register",
		newWriterRegister: "New writer? Register here",
		alreadyHaveAccount: "Already have an account? Login",
		goToDashboard: "Go to Writer Dashboard",
		writerDashboard: "Writer Dashboard",
		articleTitle: "Article Title",
		enterTitle: "Enter article title",
		category: "Category",
		selectCategory: "Select a category",
		subcategory: "Subcategory",
		selectSubcategory: "Select a subcategory",
		tags: "Tags",
		enterTags: "Enter tags (comma-separated)",
		articleContent: "Article Content",
		enterContent: "Enter your article content here",
		language: "Language",
		selectLanguage: "Select content language",
		submitArticle: "Submit Article",
		en: "English",
		am: "Amharic",
		om: "Oromo",
		writerProfile: "Writer Profile",
		editProfile: "Edit Profile",
		// settings: 'Settings',
		logout: "Log Out",
		adminDashboard: "Admin Dashboard",
		adminProfile: "Admin Profile",
		pendingReview: "Pending Review",
		approved: "Approved",
		rejected: "Rejected",
		title: "Title",
		author: "Author",
		submissionDate: "Submission Date",
		actions: "Actions",
		approve: "Approve",
		reject: "Reject",
		newArticle: "New Article",
		myArticles: "My Articles",
		status: "Status",
		pending: "Pending",
		loading: "Loading...",
		articleSubmitted: "Article Submitted",
		articleSubmittedDescription:
			"Your article has been submitted successfully and is awaiting admin approval.",
		errorSubmittingArticle: "Error Submitting Article",
		errorSubmittingArticleDescription:
			"There was an error submitting your article. Please try again.",
		articleApproved: "Article Approved",
		articleApprovedDescription:
			"The article has been approved and is now published.",
		articleRejected: "Article Rejected",
		articleRejectedDescription: "The article has been rejected.",
		errorReviewingArticle: "Error Reviewing Article",
		errorReviewingArticleDescription:
			"There was an error reviewing the article. Please try again.",
		subscribers: "Subscribers",
		errorFetchingSubscribers: "Error Fetching Subscribers",
		errorFetchingSubscribersDescription:
			"There was an error fetching the subscribers list. Please try again.",
		notProvided: "Not Provided",
		notAvailable: "N/A",
		subscriptionStart: "Subscription Start",
		subscriptionEnd: "Subscription End",
		all: "All", // Added translation for "All" category
		views: "Views",
		noArticlesFound: "No Articles Found",
		noArticlesFoundDescription:
			"There are no articles available for this category yet. Please check back later or select another category.",
		loginRequired: "Login Required",
		loginRequiredDescription: "Please log in to view this article.",
		continueToArticle: "Continue to Article",
		viewAndManageYourProfile: "View and manage your profile information",
		name: "Name",
		phone: "Phone",
		role: "Role",
		viewYourSavedArticles: "View your saved articles",
		noSavedArticles: "You haven't saved any articles yet",
		manageYourAccountSettings: "Manage your account settings",
		notifications: "Notifications",
		manageNotifications: "Manage your notification preferences",
		manage: "Manage",
		accountSettings: "Account Settings",
		manageYourAccount: "Manage your account details",
		cancel: "Cancel",
		enterYourCredentialsToLogin:
			"Enter your credentials to login to your account",
		createAnAccountToGetStarted: "Create an account to get started",
		totalViews: "Total Views",
		favoriteArticlesCount: "Favorite Articles Count",
		unsubscribe: "Unsubscribe",
		unsubscribeTooltip: "Cancel your subscription",
		unsubscribeSuccess: "You have been unsubscribed successfully.",
		failedToLogout: "Failed to logout. Please try again.",
		failedToUnsubscribe: "Failed to unsubscribe. Please try again.",
		failedToLoadFavorites:
			"Failed to load favorite articles. Please try again.",
		error: "Error",
		success: "Success",
		subscriptionDetails: "Subscription Details",
		lastBilled: "Last Billed",
		subscribedOn: "Subscribed On",
		nextActivation: "Next Activation",
		referenceNo: "Reference No.",
		contractNo: "Contract No.",
		notApplicable: "N/A",
		start: "Start",
		end: "End",
		daysRemaining: "days remaining",
		outOf: "out of",
		days: "days",
		favoriteArticles: "Favorite Articles",
		noFavoriteArticles: "No Favorite Articles",
		noFavoriteArticlesDescription:
			"You haven't saved any articles as favorites yet. Browse articles and click the heart icon to save them.",
		browseArticles: "Browse Articles",
		overview: "Overview",
		subscription: "Subscription",
		favorites: "Favorites",
		profileOverview: "Profile Overview",
		subscriptionProgress: "Subscription Progress",
		viewSubscriptionDetails: "View Subscription Details",
		subscriptionInfo: "Subscription Information",
		subscriptionInfoText:
			"Your subscription gives you access to all articles. You will be billed automatically at the end of your current period.",
		backToOverview: "Back to Overview",
		confirmUnsubscribe: "Confirm Unsubscribe",
		confirmUnsubscribeText:
			"Are you sure you want to unsubscribe? You will lose access to all content immediately.",
		// cancel: "Cancel",
		processing: "Processing...",
		// loading: "Loading...",
		active: "Active",
		// pending: "Pending",
		inactive: "Inactive",
		renew: "Renew",
		totalDays: "Total Days",
		activitySummary: "Activity Summary",
		// readMore: "Read More",

		// New translations for article page
		introduction: "Introduction",
		mainContent: "Main Content",
		conclusion: "Conclusion",
		tableOfContents: "Table of Contents",
		articleInfo: "Article Info",
		// views: "Views",
		minRead: "min read",
		// tags: "Tags",
		favorite: "Favorite",
		favorited: "Favorited",
		bookmark: "Bookmark",
		bookmarked: "Bookmarked",
		shareArticle: "Share Article",
		noArticlesFoundTitle: "No Articles Found",
		shareArticleDescription:
			"Share this article with your friends and colleagues",
		copyLink: "Copy Link",
		print: "Print",
		linkCopied: "Link Copied",
		articleLinkCopied: "Article link copied to clipboard",
		addedToFavorites: "Added to Favorites",
		articleAddedToFavorites: "Article has been added to your favorites",
		removedFromFavorites: "Removed from Favorites",
		articleRemovedFromFavorites: "Article has been removed from your favorites",
		addedToBookmarks: "Added to Bookmarks",
		articleAddedToBookmarks: "Article has been added to your bookmarks",
		removedFromBookmarks: "Removed from Bookmarks",
		articleRemovedFromBookmarks: "Article has been removed from your bookmarks",
		noRelatedArticles: "No related articles found",
		// loginRequired: "Login Required",
		// loginRequiredDescription: "Please log in to continue reading this article",
		// login: "Login",
		// register: "Register",
		// email: "Email",
		// password: "Password",
		// fullName: "Full Name",
		// phone: "Phone",
		loggingIn: "Logging in...",
		registering: "Registering...",
		noAccount: "Don't have an account?",
		registerNow: "Register now",
		// alreadyHaveAccount: "Already have an account?",
		loginNow: "Login now",
		// cancel: "Cancel",
		loginSuccess: "Login Successful",
		welcomeBack: "Welcome back!",
		loginFailed: "Login Failed",
		invalidCredentials: "Invalid email or password",
		somethingWentWrong: "Something went wrong. Please try again.",
		registrationSuccess: "Registration Successful",
		accountCreated: "Your account has been created successfully",
		registrationFailed: "Registration Failed",
		registrationError: "There was an error creating your account",
		lightMode: "Light Mode",
		darkMode: "Dark Mode",
		smallText: "Small Text",
		mediumText: "Medium Text",
		largeText: "Large Text",
		importantQuote:
			"This is an important quote from the article that highlights a key point.",
		unfavorite: "Unfavorite",
		discoverSports: "Discover Sports News",
		exploreLatestSportsNews:
			"Explore the latest sports news, updates, and stories from around the world.",
		searchArticles: "Search articles...",
		featuredStories: "Featured Stories",
		latest: "Latest",
		popular: "Popular",
		loadMore: "Load More",
		refresh: "Refresh",
		searchResults: "Search Results",
		searchingFor: "Searching for",
	},
	am: {
		home: "መነሻ",
		categories: "ምድቦች",
		profile: "መገለጫ",
		more: "ተጨማሪ",
		latestNews: "የቅርብ ጊዜ ዜና",
		featured: "ተለይቶ የቀረበ",
		search: "ፍለጋ",
		back: "ተመለስ",
		share: "አጋራ",
		likes: "ወደዱት",
		comments: "አስተያየቶች",
		save: "አስቀምጥ",
		relatedArticles: "ተዛማጅ ጽሑፎች",
		favoriteSports: "የሚወዷቸው ስፖርቶች",
		savedArticles: "የተቀመጡ ጽሑፎች",
		settings: "ቅንብሮች",
		sportsEnthusiast: "የስፖርት ወዳጅ",
		majorUpset: "በሻምፒዮንሺፕ ጨዋታ ላይ ታላቅ ድንገተኛ ሁኔታ",
		shortDescription: "የዜናው አጭር መግለጫ...",
		readMore: "ተጨማሪ ያንብቡ",
		national: "ሀገራዊ",
		international: "ዓለም አቀፍ",
		sportHistory: "የስፖርት ታሪክ",
		ethiopianAthletics: "የኢትዮጵያ አትሌቲክስ",
		football: "እግር ኳስ",
		basketball: "ቅርጫት ኳስ",
		tennis: "ቴኒስ",
		f1: "ፎርሙላ 1",
		subcategories: "ንዑስ ምድቦች",
		menu: "ምናሌ",
		becomeAWriter: "ጸሐፊ ይሁኑ",
		aboutUs: "ስለ እኛ",
		aboutUsShort: "ዴይሊ ስፖርት የቅርብ ጊዜ የስፖርት ዜናዎችን እና ዝማኔዎችን የሚያገኙበት ምንጭዎ ነው።",
		contactUs: "ያግኙን",
		termsOfUse: "የአጠቃቀም መመሪያዎች",
		getInTouch: "ያግኙን",
		writerLogin: "የጸሐፊ መግቢያ",
		writerRegister: "የጸሐፊ ምዝገባ",
		fullName: "ሙሉ ስም",
		email: "ኢሜይል",
		password: "የይለፍ ቃል",
		noArticlesFoundTitle: "መጽሐፍት አልተገኙም",
		confirmPassword: "የይለፍ ቃል ያረጋግጡ",
		login: "ግባ",
		register: "ይመዝገቡ",
		newWriterRegister: "አዲስ ጸሐፊ? እዚህ ይመዝገቡ",
		alreadyHaveAccount: "አካውንት አለዎት? ግባ",
		goToDashboard: "ወደ ጸሐፊ ዳሽቦርድ ሂድ",
		writerDashboard: "የጸሐፊ ዳሽቦርድ",
		articleTitle: "የጽሑፍ ርዕስ",
		enterTitle: "የጽሑፍ ርዕስ ያስገቡ",
		category: "ምድብ",
		selectCategory: "ምድብ ይምረጡ",
		subcategory: "ንዑስ ምድብ",
		selectSubcategory: "ንዑስ ምድብ ይምረጡ",
		tags: "መለያዎች",
		enterTags: "መለያዎችን ያስገቡ (በኮማ የተለያዩ)",
		articleContent: "የጽሑፍ ይዘት",
		enterContent: "የጽሑፍዎን ይዘት እዚህ ያስገቡ",
		language: "ቋንቋ",
		selectLanguage: "የይዘት ቋንቋ ይምረጡ",
		submitArticle: "ጽሑፍ ያስገቡ",
		en: "እንግሊዝኛ",
		am: "አማርኛ",
		om: "ኦሮምኛ",
		writerProfile: "የጸሐፊ መገለጫ",
		editProfile: "መገለጫ ያስተካክሉ",
		// settings: 'ቅንብሮች',
		logout: "ውጣ",
		adminDashboard: "የአስተዳዳሪ ዳሽቦርድ",
		adminProfile: "የአስተዳዳሪ መገለጫ",
		pendingReview: "በመገምገም ላይ",
		approved: "ተ승ድቋል",
		rejected: "ተቀባይነት አላገኘም",
		title: "ርዕስ",
		author: "ጸሐፊ",
		submissionDate: "የተላከበት ቀን",
		actions: "ድርጊቶች",
		approve: "አጽድቅ",
		reject: "ውድቅ አድርግ",
		newArticle: "አዲስ ጽሑፍ",
		myArticles: "ጽሑፎቼ",
		status: "ሁኔታ",
		pending: "በመጠባበቅ ላይ",
		loading: "በመጫን ላይ...",
		articleSubmitted: "ጽሑፍ ተልኳል",
		articleSubmittedDescription: "ጽሑፍዎ በተሳካ ሁኔታ ተልኳል እና የአስተዳዳሪ ፈቃድ እየጠበቀ ነው።",
		errorSubmittingArticle: "ጽሑፍ በመላክ ላይ ስህተት",
		errorSubmittingArticleDescription:
			"ጽሑፍዎን በመላክ ላይ ስህተት ተፈጥሯል። እባክዎ እንደገና ይሞክሩ።",
		articleApproved: "ጽሑፍ ጸድቋል",
		articleApprovedDescription: "ጽሑፉ ጸድቋል እና አሁን ታትሟል።",
		articleRejected: "ጽሑፍ ተቀባይነት አላገኘም",
		articleRejectedDescription: "ጽሑፉ ተቀባይነት አላገኘም።",
		errorReviewingArticle: "ጽሑፍን በመገምገም ላይ ስህተት",
		errorReviewingArticleDescription:
			"ጽሑፉን በመገምገም ላይ ስህተት ተፈጥሯል። እባክዎ እንደገና ይሞክሩ።",
		all: "ሁሉም", // Added translation for "All" category
		views: "ተመልካቾች",
		noArticlesFound: "ምንም ጽሑፎች አልተገኙም",
		noArticlesFoundDescription:
			"ለዚህ ምድብ የሚገኙ ጽሑፎች የሉም። እባክዎ በኋላ ይመልከቱ ወይም ሌላ ምድብ ይምረጡ።",
		loginRequired: "መግቢያ ያስፈልጋል",
		loginRequiredDescription: "እባክዎ ይህን ጽሑፍ ለማየት ይግቡ።",
		continueToArticle: "ወደ ጽሑፍ ይቀጥሉ",
		viewAndManageYourProfile: "የመገለጫ መረጃዎን ይመልከቱ እና ያስተዳድሩ",
		name: "ስም",
		phone: "ስልክ",
		role: "ሚና",
		viewYourSavedArticles: "የተቀመጡ ጽሑፎችዎን ይመልከቱ",
		noSavedArticles: "እስካሁን ምንም ጽሑፎችን አልቀመጡም",
		manageYourAccountSettings: "የመለያ ቅንብሮችዎን ያስተዳድሩ",
		notifications: "ማሳወቂያዎች",
		manageNotifications: "የማሳወቂያ ምርጫዎችዎን ያስተዳድሩ",
		manage: "አስተዳድር",
		accountSettings: "የመለያ ቅንብሮች",
		manageYourAccount: "የመለያ ዝርዝሮችዎን ያስተዳድሩ",
		cancel: "ይቅር",
		enterYourCredentialsToLogin: "ወደ መለያዎ ለመግባት ምስክርዎን ያስገቡ",
		createAnAccountToGetStarted: "ለመጀመር መለያ ይፍጠሩ",
		totalViews: "ጠቅላላ እይታዎች",
		favoriteArticlesCount: "የተወዳጅ ጽሑፎች ብዛት",
		unsubscribe: "ምዝገባ ይሰርዙ",
		unsubscribeTooltip: "ምዝገባዎን ይሰርዙ",
		unsubscribeSuccess: "ምዝገባዎን በተሳካ ሁኔታ ሰርዘዋል።",
		failedToLogout: "መውጣት አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
		failedToUnsubscribe: "ምዝገባን መሰረዝ አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
		failedToLoadFavorites: "የተወዳጅ ጽሑፎችን መጫን አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
		error: "ስህተት",
		success: "ተሳክቷል",
		subscriptionDetails: "የምዝገባ ዝርዝሮች",
		lastBilled: "የመጨረሻ ክፍያ",
		subscribedOn: "የተመዘገቡበት ቀን",
		nextActivation: "ቀጣይ ማግበር",
		referenceNo: "የማጣቀሻ ቁጥር",
		contractNo: "የውል ቁጥር",
		notApplicable: "አይመለከትም",
		start: "መጀመሪያ",
		end: "መጨረሻ",
		daysRemaining: "ቀናት ቀርተዋል",
		outOf: "ከ",
		days: "ቀናት",
		favoriteArticles: "የተወዳጅ ጽሑፎች",
		noFavoriteArticles: "ምንም የተወዳጅ ጽሑፎች የሉም",
		noFavoriteArticlesDescription:
			"እስካሁን ምንም ጽሑፎችን እንደ ተወዳጅ አላስቀመጡም። ጽሑፎችን ይመልከቱ እና ለማስቀመጥ የልብ አዶውን ጠቅ ያድርጉ።",
		browseArticles: "ጽሑፎችን ይመልከቱ",
		overview: "አጠቃላይ እይታ",
		subscription: "ምዝገባ",
		favorites: "ተወዳጆች",
		profileOverview: "የመገለጫ አጠቃላይ እይታ",
		subscriptionProgress: "የምዝገባ እድገት",
		viewSubscriptionDetails: "የምዝገባ ዝርዝሮችን ይመልከቱ",
		subscriptionInfo: "የምዝገባ መረጃ",
		subscriptionInfoText:
			"ምዝገባዎ ሁሉንም ጽሑፎች የማግኘት መብት ይሰጥዎታል። በአሁኑ ጊዜ መጨረሻ ላይ በራስ-ሰር ክፍያ ይከፈላል።",
		backToOverview: "ወደ አጠቃላይ እይታ ተመለስ",
		confirmUnsubscribe: "ምዝገባ መሰረዝን ያረጋግጡ",
		confirmUnsubscribeText:
			"ምዝገባዎን መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት? ወዲያውኑ ለሁሉም ይዘት መዳረሻን ያጣሉ።",
		// cancel: "ይቅር",
		processing: "በማስኬድ ላይ...",
		// loading: "በመጫን ላይ...",
		active: "ንቁ",
		// pending: "በመጠባበቅ ላይ",
		inactive: "ንቁ ያልሆነ",
		renew: "አድስ",
		totalDays: "ጠቅላላ ቀናት",
		activitySummary: "የእንቅስቃሴ ማጠቃለያ",
		// readMore: "ተጨማሪ ያንብቡ",

		// New translations for article page
		introduction: "መግቢያ",
		mainContent: "ዋና ይዘት",
		conclusion: "ማጠቃለያ",
		tableOfContents: "የይዘት ሰንጠረዥ",
		articleInfo: "የጽሑፍ መረጃ",
		// views: "ተመልካቾች",
		minRead: "ደቂቃ ንባብ",
		// tags: "መለያዎች",
		favorite: "ወደድኩት",
		favorited: "የወደድኩት",
		bookmark: "ምልክት አድርግ",
		bookmarked: "ምልክት ተደርጓል",
		shareArticle: "ጽሑፍን አጋራ",
		shareArticleDescription: "ይህን ጽሑፍ ከጓደኞችዎ እና ከሥራ ባልደረቦችዎ ጋር ያጋሩ",
		copyLink: "አገናኝ ቅዳ",
		print: "አትም",
		linkCopied: "አገናኝ ተቀድቷል",
		articleLinkCopied: "የጽሑፍ አገናኝ ወደ ቅንጥብ ሰሌዳ ተቀድቷል",
		addedToFavorites: "ወደ ተወዳጆች ታክሏል",
		articleAddedToFavorites: "ጽሑፉ ወደ ተወዳጆችዎ ታክሏል",
		removedFromFavorites: "ከተወዳጆች ተወግዷል",
		articleRemovedFromFavorites: "ጽሑፉ ከተወዳጆችዎ ተወግዷል",
		addedToBookmarks: "ወደ ምልክቶች ታክሏል",
		articleAddedToBookmarks: "ጽሑፉ ወደ ምልክቶችዎ ታክሏል",
		removedFromBookmarks: "ከምልክቶች ተወግዷል",
		articleRemovedFromBookmarks: "ጽሑፉ ከምልክቶችዎ ተወግዷል",
		noRelatedArticles: "ምንም ተዛማጅ ጽሑፎች አልተገኙም",
		// loginRequired: "መግቢያ ያስፈልጋል",
		// loginRequiredDescription: "እባክዎ ይህን ጽሑፍ ለማንበብ ይግቡ",
		// login: "ግባ",
		// register: "ይመዝገቡ",
		// email: "ኢሜይል",
		// password: "የይለፍ ቃል",
		// fullName: "ሙሉ ስም",
		// phone: "ስልክ",
		loggingIn: "በመግባት ላይ...",
		registering: "በመመዝገብ ላይ...",
		noAccount: "መለያ የለዎትም?",
		registerNow: "አሁን ይመዝገቡ",
		// alreadyHaveAccount: "መለያ አለዎት?",
		loginNow: "አሁን ይግቡ",
		// cancel: "ይቅር",
		loginSuccess: "መግባት ተሳክቷል",
		welcomeBack: "እንኳን ደህና መጡ!",
		loginFailed: "መግባት አልተሳካም",
		invalidCredentials: "ልክ ያልሆነ ኢሜይል ወይም የይለፍ ቃል",
		somethingWentWrong: "የሆነ ስህተት ተከስቷል። እባክዎ እንደገና ይሞክሩ።",
		registrationSuccess: "ምዝገባ ተሳክቷል",
		accountCreated: "መለያዎ በተሳካ ሁኔታ ተፈጥሯል",
		registrationFailed: "ምዝገባ አልተሳካም",
		registrationError: "መለያዎን በመፍጠር ላይ ስህተት ነበር",
		lightMode: "ብርሃን ሁነታ",
		darkMode: "ጨለማ ሁነታ",
		smallText: "ትንሽ ጽሑፍ",
		mediumText: "መካከለኛ ጽሑፍ",
		largeText: "ትልቅ ጽሑፍ",
		importantQuote: "ይህ ከጽሑፉ የተወሰደ አስፈላጊ ጥቅስ ሲሆን ዋና ነጥብን ያጎላል።",
		unfavorite: "አልወደድኩትም",
		discoverSports: "የስፖርት ዜናዎችን ይፈልጉ",
		exploreLatestSportsNews:
			"ከዓለም ዙሪያ የቅርብ ጊዜ የስፖርት ዜናዎችን፣ ዝማኔዎችን እና ታሪኮችን ያስሱ።",
		searchArticles: "ጽሑፎችን ይፈልጉ...",
		featuredStories: "ተለይተው የቀረቡ ታሪኮች",
		latest: "የቅርብ ጊዜ",
		popular: "ታዋቂ",
		loadMore: "ተጨማሪ ጫን",
		refresh: "አድስ",
		searchResults: "የፍለጋ ውጤቶች",
		searchingFor: "በመፈለግ ላይ",
	},
	om: {
		home: "Mana",
		categories: "Ramaddii",
		profile: "Eenyummeessa",
		more: "Dabalata",
		latestNews: "Oduu Haaraa",
		featured: "Kan Filatame",
		search: "Barbaadi",
		back: "Duubatti",
		share: "Qoodi",
		likes: "Jaallatamaa",
		comments: "Yaada",
		save: "Kuadhu",
		relatedArticles: "Barreeffamoota Walfakkaataa",
		favoriteSports: "Ispoortii Jaallatamaa",
		savedArticles: "Barreeffamoota Kuufame",
		// settings: 'Qindaa'ina',
		sportsEnthusiast: "Shaakalaa Ispoortii",
		majorUpset: "Moo'ii Guddaa Taphoota Injifannoo",
		shortDescription: "Ibsa gabaabaa odeeffannoo...",
		readMore: "Dabalataan Dubbisi",
		national: "Biyya Keessaa",
		international: "Addunyaa",
		sportHistory: "Seenaa Ispoortii",
		ethiopianAthletics: "Atleetiksii Itoophiyaa",
		football: "Kubbaa Miilaa",
		basketball: "Kubbaa Harkaa",
		tennis: "Tenisii",
		f1: "Formula 1",
		subcategories: "Ramaddii Xiqqaa",
		menu: "Menu",
		becomeAWriter: "Barreessaa Ta'uu",
		aboutUs: "Waa'ee Keenya",
		noArticlesFoundTitle: "No Articles Found",
		aboutUsShort:
			"Daily Sport madda oduu fi odeeffannoo ispoortii haaraa argattanidha.",
		contactUs: "Nu Quunnamaa",
		termsOfUse: "Haala Itti Fayyadama",
		getInTouch: "Nu Quunnamaa",
		writerLogin: "Seensa Barreessaa",
		writerRegister: "Galmee Barreessaa",
		fullName: "Maqaa Guutuu",
		email: "Imeelii",
		password: "Jecha Icciitii",
		confirmPassword: "Jecha Icciitii Mirkaneessi",
		login: "Seeni",
		register: "Galmaa'i",
		newWriterRegister: "Barreessaa haaraa? Asitti galmaa'i",
		alreadyHaveAccount: "Herrega qabdaa? Seeni",
		goToDashboard: "Gara Dashboordii Barreessaatti Deemai",
		writerDashboard: "Dashboordii Barreessaa",
		articleTitle: "Mata Duree Barreeffamaa",
		enterTitle: "Mata duree barreeffamaa galchi",
		category: "Ramaddii",
		selectCategory: "Ramaddii filadhu",
		subcategory: "Ramaddii Xiqqaa",
		selectSubcategory: "Ramaddii xiqqaa filadhu",
		tags: "Taagiwwan",
		enterTags: "Taagiwwan galchi (comma-tiin adda bahan)",
		articleContent: "Qabiyyee Barreeffamaa",
		enterContent: "Qabiyyee barreeffama kee asitti galchi",
		language: "Afaan",
		selectLanguage: "Afaan qabiyyee filadhu",
		submitArticle: "Barreeffama Galchi",
		en: "Afaan Ingilizii",
		am: "Afaan Amaaraa",
		om: "Afaan Oromoo",
		writerProfile: "Profaayilii Barreessaa",
		editProfile: "Profaayilii Gulaali",
		settings: "Qindaa'ina",
		logout: "Ba'i",
		adminDashboard: "Dashboordii Bulchiinsaa",
		adminProfile: "Profaayilii Bulchaa",
		pendingReview: "Sakatta'amu Irra Jiru",
		approved: "Fudhatameera",
		rejected: "Fudhatama Dhabeera",
		title: "Mata Duree",
		author: "Barreessaa",
		submissionDate: "Guyyaa Dhiyaate",
		actions: "Tarkaanfiiwwan",
		approve: "Fudhadhu",
		reject: "Diduu",
		newArticle: "Barreeffama Haaraa",
		myArticles: "Barreeffamoota Koo",
		status: "Haala",
		pending: "Eegamaa Jiru",
		loading: "Fe'aa jira...",
		articleSubmitted: "Barreeffamni Ergameera",
		articleSubmittedDescription:
			"Barreeffamni keessan milkaa'inaan ergameera, eeyyama bulchiinsaa eeggataa jira.",
		errorSubmittingArticle: "Barreeffama Erguu Keessatti Dogoggora",
		errorSubmittingArticleDescription:
			"Barreeffama keessan erguu keessatti dogoggorri uumameera. Maaloo irra deebi'aadhaa yaali.",
		articleApproved: "Barreeffamni Fudhatameera",
		articleApprovedDescription:
			"Barreeffamni fudhatameera, amma maxxanfameera.",
		articleRejected: "Barreeffamni Fudhatama Dhabeera",
		articleRejectedDescription: "Barreeffamni fudhatama dhabeera.",
		errorReviewingArticle: "Barreeffama Ilaaluu Keessatti Dogoggora",
		errorReviewingArticleDescription:
			"Barreeffama ilaaluu keessatti dogoggorri uumameera. Maaloo irra deebi'aadhaa yaali.",
		all: "Hunda", // Added translation for "All" category
		views: "Ilaaltoota",
		noArticlesFound: "Barreeffamni Hin Argamne",
		noArticlesFoundDescription:
			"Ramaddii kanaaf barreeffamni hin jiru. Maaloo yeroo gara fuulduraatti ilaalaa ykn ramaddii biraa filadhu.",
		loginRequired: "Seensa Barbaachisaadha",
		loginRequiredDescription: "Maaloo barreeffama kana ilaaluuf seeni.",
		continueToArticle: "Gara Barreeffamaatti Itti Fufi",
		viewAndManageYourProfile: "Odeeffannoo profaayilii kee ilaali fi to'adhu",
		name: "Maqaa",
		phone: "Bilbila",
		role: "Gahee",
		viewYourSavedArticles: "Barreeffamoota kuufame ilaali",
		noSavedArticles: "Hanga ammaatti barreeffama hin kuufamne",
		manageYourAccountSettings: "Qindaa'ina herrega kee to'adhu",
		notifications: "Beeksisawwan",
		manageNotifications: "Filannoo beeksisaa kee to'adhu",
		manage: "To'adhu",
		accountSettings: "Qindaa'ina Herregaa",
		manageYourAccount: "Odeeffannoo herrega kee to'adhu",
		cancel: "Haqi",
		enterYourCredentialsToLogin: "Herrega keetti seenuuf ragaa kee galchi",
		createAnAccountToGetStarted: "Jalqabuuf herrega uumi",
		totalViews: "Ilaaltoota Waliigalaa",
		favoriteArticlesCount: "Baay'ina Barreeffamoota Jaallatamoo",
		unsubscribe: "Maqaa Baasi",
		unsubscribeTooltip: "Maqaa galmee keessaa haqi",
		unsubscribeSuccess: "Milkaa'inaan maqaa galmee keessaa haqameera.",
		failedToLogout: "Ba'uun hin milkoofne. Maaloo irra deebi'i yaali.",
		failedToUnsubscribe:
			"Maqaa galmee keessaa haquun hin milkoofne. Maaloo irra deebi'i yaali.",
		failedToLoadFavorites:
			"Barreeffamoota jaallatamoo fe'uun hin milkoofne. Maaloo irra deebi'i yaali.",
		error: "Dogoggora",
		success: "Milkaa'ina",
		subscriptionDetails: "Ibsa Galmee",
		lastBilled: "Kaffaltii Dhumaa",
		subscribedOn: "Guyyaa Galmaa'e",
		nextActivation: "Hojii Irra Oolmaa Itti Aanu",
		referenceNo: "Lakkoofsa Wabii",
		contractNo: "Lakkoofsa Waliigaltee",
		notApplicable: "Hin Ilaallatu",
		start: "Jalqaba",
		end: "Dhuma",
		daysRemaining: "guyyoota hafe",
		outOf: "keessaa",
		days: "guyyoota",
		favoriteArticles: "Barreeffamoota Jaallatamoo",
		noFavoriteArticles: "Barreeffamni Jaallatamaan Hin Jiru",
		noFavoriteArticlesDescription:
			"Hanga ammaatti barreeffamoota akka jaallatamaa hin kuufamne. Barreeffamoota ilaalaa fi kuufachuuf mallattoo onnee cuqaasaa.",
		browseArticles: "Barreeffamoota Ilaali",
		overview: "Ibsa Waliigalaa",
		subscription: "Galmee",
		favorites: "Jaallatamoo",
		profileOverview: "Ibsa Waliigalaa Profaayilii",
		subscriptionProgress: "Guutuu Galmee",
		viewSubscriptionDetails: "Ibsa Galmee Ilaali",
		subscriptionInfo: "Odeeffannoo Galmee",
		subscriptionInfoText:
			"Galmeen kee barreeffamoota hundaaf argachuu siif kenna. Yeroo amma kee dhuma irratti ofumaan kaffaltiin si irraa fudhatama.",
		backToOverview: "Gara Ibsa Waliigalaatti Deebi'i",
		confirmUnsubscribe: "Maqaa Baasuu Mirkaneessi",
		confirmUnsubscribeText: "",
		// New translations for article page
		introduction: "Seensa",
		mainContent: "Qabiyyee Ijoo",
		conclusion: "Guduunfaa",
		tableOfContents: "Gabatee Qabiyyee",
		articleInfo: "Odeeffannoo Barreeffamaa",
		// views: "Ilaaltoota",
		minRead: "daqiiqaa dubbisa",
		// tags: "Taagiwwan",
		favorite: "Jaallachuu",
		favorited: "Jaallatameera",
		bookmark: "Kaa'i",
		bookmarked: "Kaa'ameera",
		shareArticle: "Barreeffama Qoodi",
		shareArticleDescription:
			"Barreeffama kana hiriyoota fi hojjettoota kee waliin qoodi",
		copyLink: "Geessituu Garagalchi",
		print: "Maxxansi",
		linkCopied: "Geessituun Garagalfameera",
		articleLinkCopied: "Geessituun barreeffamaa gara clipboard garagalfameera",
		addedToFavorites: "Gara Jaallatamtoota Dabalameera",
		articleAddedToFavorites: "Barreeffamni gara jaallatamtoota kee dabalameera",
		removedFromFavorites: "Jaallatamtoota Keessaa Haqameera",
		articleRemovedFromFavorites:
			"Barreeffamni jaallatamtoota kee keessaa haqameera",
		addedToBookmarks: "Gara Kaa'amtoota Dabalameera",
		articleAddedToBookmarks: "Barreeffamni gara kaa'amtoota kee dabalameera",
		removedFromBookmarks: "Kaa'amtoota Keessaa Haqameera",
		articleRemovedFromBookmarks:
			"Barreeffamni kaa'amtoota kee keessaa haqameera",
		noRelatedArticles: "Barreeffamoota walfakkaatan hin argamne",

		loggingIn: "Seenaa jira...",
		registering: "Galmaa'aa jira...",
		noAccount: "Herrega hin qabdu?",
		registerNow: "Amma galmaa'i",
		// alreadyHaveAccount: "Duraan herrega qabdaa?",
		loginNow: "Amma seeni",
		// cancel: "Haqi",
		loginSuccess: "Seensi Milkaa'e",
		welcomeBack: "Baga nagaan dhufte!",
		loginFailed: "Seensi Hin Milkoofne",
		invalidCredentials: "Imeelii ykn jecha icciitii dogoggora",
		somethingWentWrong: "Dogoggorri uumameera. Maaloo irra deebi'i yaali.",
		registrationSuccess: "Galmeen Milkaa'e",
		accountCreated: "Herregni kee milkaa'inaan uumameera",
		registrationFailed: "Galmeen Hin Milkoofne",
		registrationError: "Herrega kee uumuun dogoggora qabaachuu danda'a",
		lightMode: "Haala Ifa",
		darkMode: "Haala Dukkana",
		smallText: "Barreeffama Xinnaa",
		mediumText: "Barreeffama Giddugaleessa",
		largeText: "Barreeffama Guddaa",
		importantQuote:
			"Kun waraabbii barbaachisaa barreeffama kana keessaa kan yaada ijoo ibsuudha.",
		unfavorite: "Jaallatamummaa Baasi",
		discoverSports: "Oduu Ispoortii Argadhu",
		exploreLatestSportsNews:
			"Oduu ispoortii, odeeffannoo haaraa, fi seenaa addunyaa guutuu irraa argamu sakatta'i.",
		searchArticles: "Barreeffamoota barbaadi...",
		featuredStories: "Seenaalee Filatamoo",
		latest: "Kan Haaraa",
		popular: "Kan Beekamaa",
		loadMore: "Dabalata Fe'i",
		refresh: "Haaromsi",
		searchResults: "Bu'aa Barbaacha",
		searchingFor: "Kan Barbaadamu",
	},
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
	children,
}) => {
	const [language, setLanguage] = useState<Language>("en");

	useEffect(() => {
		const savedLanguage = localStorage.getItem("language") as Language;
		if (savedLanguage) {
			setLanguage(savedLanguage);
		}
	}, []);

	const changeLanguage = (lang: Language) => {
		setLanguage(lang);
		localStorage.setItem("language", lang);
	};

	const t = (key: string) => {
		return translations[language][key] || key;
	};

	return (
		<LanguageContext.Provider
			value={{ language, setLanguage: changeLanguage, t }}>
			{children}
		</LanguageContext.Provider>
	);
};

export const useLanguage = () => {
	const context = useContext(LanguageContext);
	if (context === undefined) {
		throw new Error("useLanguage must be used within a LanguageProvider");
	}
	return context;
};
