"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "am" | "om";

type LanguageContextType = {
	language: Language;
	setLanguage: (lang: Language) => void;
	t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(
	undefined
);

const translations: Record<Language, Record<string, string>> = {
	en: {
		home: "Home",
		categories: "Categories",
		profile: "Profile",
		more: "More",
		latestNews: "Latest News",
		featured: "Featured",
		search: "Search",
		back: "Back",
		share: "Share",
		likes: "Likes",
		comments: "Comments",
		save: "Save",
		relatedArticles: "Related Articles",
		favoriteSports: "Favorite Sports",
		savedArticles: "Saved Articles",
		settings: "Settings",
		sportsEnthusiast: "Sports Enthusiast",
		majorUpset: "Major Upset in Championship Game",
		shortDescription: "Short description of the news item...",
		readMore: "Read More",
		national: "National",
		international: "International",
		sportHistory: "Sport History",
		ethiopianAthletics: "Ethiopian Athletics",
		football: "Football",
		basketball: "Basketball",
		tennis: "Tennis",
		f1: "F1",
		subcategories: "Subcategories",
		menu: "Menu",
		becomeAWriter: "Become a Writer",
		aboutUs: "About Us",
		aboutUsShort:
			"Daily Sport is your go-to source for the latest sports news and updates.",
		contactUs: "Contact Us",
		termsOfUse: "Terms of Use",
		getInTouch: "Get In Touch",
		writerLogin: "Writer Login",
		writerRegister: "Writer Registration",
		fullName: "Full Name",
		email: "Email",
		password: "Password",
		confirmPassword: "Confirm Password",
		login: "Login",
		register: "Register",
		newWriterRegister: "New writer? Register here",
		alreadyHaveAccount: "Already have an account? Login",
		goToDashboard: "Go to Writer Dashboard",
		writerDashboard: "Writer Dashboard",
		articleTitle: "Article Title",
		enterTitle: "Enter article title",
		category: "Category",
		selectCategory: "Select a category",
		subcategory: "Subcategory",
		selectSubcategory: "Select a subcategory",
		tags: "Tags",
		enterTags: "Enter tags (comma-separated)",
		articleContent: "Article Content",
		enterContent: "Enter your article content here",
		language: "Language",
		selectLanguage: "Select content language",
		submitArticle: "Submit Article",
		en: "English",
		am: "Amharic",
		om: "Oromo",
		writerProfile: "Writer Profile",
		editProfile: "Edit Profile",
		// settings: 'Settings',
		logout: "Log Out",
		adminDashboard: "Admin Dashboard",
		adminProfile: "Admin Profile",
		pendingReview: "Pending Review",
		approved: "Approved",
		rejected: "Rejected",
		title: "Title",
		author: "Author",
		submissionDate: "Submission Date",
		actions: "Actions",
		approve: "Approve",
		reject: "Reject",
		newArticle: "New Article",
		myArticles: "My Articles",
		status: "Status",
		pending: "Pending",
		loading: "Loading...",
		articleSubmitted: "Article Submitted",
		articleSubmittedDescription:
			"Your article has been submitted successfully and is awaiting admin approval.",
		errorSubmittingArticle: "Error Submitting Article",
		errorSubmittingArticleDescription:
			"There was an error submitting your article. Please try again.",
		articleApproved: "Article Approved",
		articleApprovedDescription:
			"The article has been approved and is now published.",
		articleRejected: "Article Rejected",
		articleRejectedDescription: "The article has been rejected.",
		errorReviewingArticle: "Error Reviewing Article",
		errorReviewingArticleDescription:
			"There was an error reviewing the article. Please try again.",
	},
	am: {
		home: "መነሻ",
		categories: "ምድቦች",
		profile: "መገለጫ",
		more: "ተጨማሪ",
		latestNews: "የቅርብ ጊዜ ዜና",
		featured: "ተለይቶ የቀረበ",
		search: "ፍለガ",
		back: "ተመለስ",
		share: "አጋራ",
		likes: "ወደዱት",
		comments: "አስተያየቶች",
		save: "አስቀምጥ",
		relatedArticles: "ተዛማጅ ጽሑፎች",
		favoriteSports: "የሚወዷቸው ስፖርቶች",
		savedArticles: "የተቀመጡ ጽሑፎች",
		settings: "ቅንብሮች",
		sportsEnthusiast: "የስፖርት ወዳጅ",
		majorUpset: "በሻምፒዮንሺፕ ጨዋታ ላይ ታላቅ ድንገተኛ ሁኔታ",
		shortDescription: "የዜናው አጭር መግለጫ...",
		readMore: "ተጨማሪ ያንብቡ",
		national: "ሀገራዊ",
		international: "ዓለም አቀፍ",
		sportHistory: "የስፖርት ታሪክ",
		ethiopianAthletics: "የኢትዮጵያ አትሌቲክስ",
		football: "እግር ኳስ",
		basketball: "ቅርጫት ኳስ",
		tennis: "ቴኒስ",
		f1: "ፎርሙላ 1",
		subcategories: "ንዑስ ምድቦች",
		menu: "ምናሌ",
		becomeAWriter: "ጸሐፊ ይሁኑ",
		aboutUs: "ስለ እኛ",
		aboutUsShort: "ዴይሊ ስፖርት የቅርብ ጊዜ የስፖርት ዜናዎችን እና ዝማኔዎችን የሚያገኙበት ምንጭዎ ነው።",
		contactUs: "ያግኙን",
		termsOfUse: "የአጠቃቀም መመሪያዎች",
		getInTouch: "ያግኙን",
		writerLogin: "የጸሐፊ መግቢያ",
		writerRegister: "የጸሐፊ ምዝገባ",
		fullName: "ሙሉ ስም",
		email: "ኢሜይል",
		password: "የይለፍ ቃል",
		confirmPassword: "የይለፍ ቃል ያረጋግጡ",
		login: "ግባ",
		register: "ይመዝገቡ",
		newWriterRegister: "አዲስ ጸሐፊ? እዚህ ይመዝገቡ",
		alreadyHaveAccount: "አካውንት አለዎት? ግባ",
		goToDashboard: "ወደ ጸሐፊ ዳሽቦርድ ሂድ",
		writerDashboard: "የጸሐፊ ዳሽቦርድ",
		articleTitle: "የጽሑፍ ርዕስ",
		enterTitle: "የጽሑፍ ርዕስ ያስገቡ",
		category: "ምድብ",
		selectCategory: "ምድብ ይምረጡ",
		subcategory: "ንዑስ ምድብ",
		selectSubcategory: "ንዑስ ምድብ ይምረጡ",
		tags: "መለያዎች",
		enterTags: "መለያዎችን ያስገቡ (በኮማ የተለያዩ)",
		articleContent: "የጽሑፍ ይዘት",
		enterContent: "የጽሑፍዎን ይዘት እዚህ ያስገቡ",
		language: "ቋንቋ",
		selectLanguage: "የይዘት ቋንቋ ይምረጡ",
		submitArticle: "ጽሑፍ ያስገቡ",
		en: "እንግሊዝኛ",
		am: "አማርኛ",
		om: "ኦሮምኛ",
		writerProfile: "የጸሐፊ መገለጫ",
		editProfile: "መገለጫ ያስተካክሉ",
		// settings: 'ቅንብሮች',
		logout: "ውጣ",
		adminDashboard: "የአስተዳዳሪ ዳሽቦርድ",
		adminProfile: "የአስተዳዳሪ መገለጫ",
		pendingReview: "በመገምገም ላይ",
		approved: "ተ승ድቋል",
		rejected: "ተቀባይነት አላገኘም",
		title: "ርዕስ",
		author: "ጸሐፊ",
		submissionDate: "የተላከበት ቀን",
		actions: "ድርጊቶች",
		approve: "አጽድቅ",
		reject: "ውድቅ አድርግ",
		newArticle: "አዲስ ጽሑፍ",
		myArticles: "ጽሑፎቼ",
		status: "ሁኔታ",
		pending: "በመጠባበቅ ላይ",
		loading: "በመጫን ላይ...",
		articleSubmitted: "ጽሑፍ ተልኳል",
		articleSubmittedDescription: "ጽሑፍዎ በተሳካ ሁኔታ ተልኳል እና የአስተዳዳሪ ፈቃድ እየጠበቀ ነው።",
		errorSubmittingArticle: "ጽሑፍ በመላክ ላይ ስህተት",
		errorSubmittingArticleDescription:
			"ጽሑፍዎን በመላክ ላይ ስህተት ተፈጥሯል። እባክዎ እንደገና ይሞክሩ።",
		articleApproved: "ጽሑፍ ጸድቋል",
		articleApprovedDescription: "ጽሑፉ ጸድቋል እና አሁን ታትሟል።",
		articleRejected: "ጽሑፍ ተቀባይነት አላገኘም",
		articleRejectedDescription: "ጽሑፉ ተቀባይነት አላገኘም።",
		errorReviewingArticle: "ጽሑፍን በመገምገም ላይ ስህተት",
		errorReviewingArticleDescription:
			"ጽሑፉን በመገምገም ላይ ስህተት ተፈጥሯል። እባክዎ እንደገና ይሞክሩ።",
	},
	om: {
		home: "Mana",
		categories: "Ramaddii",
		profile: "Eenyummeessa",
		more: "Dabalata",
		latestNews: "Oduu Haaraa",
		featured: "Kan Filatame",
		search: "Barbaadi",
		back: "Duubatti",
		share: "Qoodi",
		likes: "Jaallatamaa",
		comments: "Yaada",
		save: "Kuadhu",
		relatedArticles: "Barreeffamoota Walfakkaataa",
		favoriteSports: "Ispoortii Jaallatamaa",
		savedArticles: "Barreeffamoota Kuufame",
		// settings: 'Qindaa'ina',
		sportsEnthusiast: "Shaakalaa Ispoortii",
		majorUpset: "Moo'ii Guddaa Taphoota Injifannoo",
		shortDescription: "Ibsa gabaabaa odeeffannoo...",
		readMore: "Dabalataan Dubbisi",
		national: "Biyya Keessaa",
		international: "Addunyaa",
		sportHistory: "Seenaa Ispoortii",
		ethiopianAthletics: "Atleetiksii Itoophiyaa",
		football: "Kubbaa Miilaa",
		basketball: "Kubbaa Harkaa",
		tennis: "Tenisii",
		f1: "Formula 1",
		subcategories: "Ramaddii Xiqqaa",
		menu: "Menu",
		becomeAWriter: "Barreessaa Ta'uu",
		aboutUs: "Waa'ee Keenya",
		aboutUsShort:
			"Daily Sport madda oduu fi odeeffannoo ispoortii haaraa argattanidha.",
		contactUs: "Nu Quunnamaa",
		termsOfUse: "Haala Itti Fayyadama",
		getInTouch: "Nu Quunnamaa",
		writerLogin: "Seensa Barreessaa",
		writerRegister: "Galmee Barreessaa",
		fullName: "Maqaa Guutuu",
		email: "Imeelii",
		password: "Jecha Icciitii",
		confirmPassword: "Jecha Icciitii Mirkaneessi",
		login: "Seeni",
		register: "Galmaa'i",
		newWriterRegister: "Barreessaa haaraa? Asitti galmaa'i",
		alreadyHaveAccount: "Herrega qabdaa? Seeni",
		goToDashboard: "Gara Dashboordii Barreessaatti Deemai",
		writerDashboard: "Dashboordii Barreessaa",
		articleTitle: "Mata Duree Barreeffamaa",
		enterTitle: "Mata duree barreeffamaa galchi",
		category: "Ramaddii",
		selectCategory: "Ramaddii filadhu",
		subcategory: "Ramaddii Xiqqaa",
		selectSubcategory: "Ramaddii xiqqaa filadhu",
		tags: "Taagiwwan",
		enterTags: "Taagiwwan galchi (comma-tiin adda bahan)",
		articleContent: "Qabiyyee Barreeffamaa",
		enterContent: "Qabiyyee barreeffama kee asitti galchi",
		language: "Afaan",
		selectLanguage: "Afaan qabiyyee filadhu",
		submitArticle: "Barreeffama Galchi",
		en: "Afaan Ingilizii",
		am: "Afaan Amaaraa",
		om: "Afaan Oromoo",
		writerProfile: "Profaayilii Barreessaa",
		editProfile: "Profaayilii Gulaali",
		settings: "Qindaa'ina",
		logout: "Ba'i",
		adminDashboard: "Dashboordii Bulchiinsaa",
		adminProfile: "Profaayilii Bulchaa",
		pendingReview: "Sakatta'amu Irra Jiru",
		approved: "Fudhatameera",
		rejected: "Fudhatama Dhabeera",
		title: "Mata Duree",
		author: "Barreessaa",
		submissionDate: "Guyyaa Dhiyaate",
		actions: "Tarkaanfiiwwan",
		approve: "Fudhadhu",
		reject: "Diduu",
		newArticle: "Barreeffama Haaraa",
		myArticles: "Barreeffamoota Koo",
		status: "Haala",
		pending: "Eegamaa Jiru",
		loading: "Fe'aa jira...",
		articleSubmitted: "Barreeffamni Ergameera",
		articleSubmittedDescription:
			"Barreeffamni keessan milkaa'inaan ergameera, eeyyama bulchiinsaa eeggataa jira.",
		errorSubmittingArticle: "Barreeffama Erguu Keessatti Dogoggora",
		errorSubmittingArticleDescription:
			"Barreeffama keessan erguu keessatti dogoggorri uumameera. Maaloo irra deebi'aadhaa yaali.",
		articleApproved: "Barreeffamni Fudhatameera",
		articleApprovedDescription:
			"Barreeffamni fudhatameera, amma maxxanfameera.",
		articleRejected: "Barreeffamni Fudhatama Dhabeera",
		articleRejectedDescription: "Barreeffamni fudhatama dhabeera.",
		errorReviewingArticle: "Barreeffama Ilaaluu Keessatti Dogoggora",
		errorReviewingArticleDescription:
			"Barreeffama ilaaluu keessatti dogoggorri uumameera. Maaloo irra deebi'aadhaa yaali.",
	},
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
	children,
}) => {
	const [language, setLanguage] = useState<Language>("en");

	useEffect(() => {
		const savedLanguage = localStorage.getItem("language") as Language;
		if (savedLanguage) {
			setLanguage(savedLanguage);
		}
	}, []);

	const changeLanguage = (lang: Language) => {
		setLanguage(lang);
		localStorage.setItem("language", lang);
	};

	const t = (key: string) => {
		return translations[language][key] || key;
	};

	return (
		<LanguageContext.Provider
			value={{ language, setLanguage: changeLanguage, t }}>
			{children}
		</LanguageContext.Provider>
	);
};

export const useLanguage = () => {
	const context = useContext(LanguageContext);
	if (context === undefined) {
		throw new Error("useLanguage must be used within a LanguageProvider");
	}
	return context;
};
